// Generated by gencpp from file client_server/project1.msg
// DO NOT EDIT!


#ifndef CLIENT_SERVER_MESSAGE_PROJECT1_H
#define CLIENT_SERVER_MESSAGE_PROJECT1_H

#include <ros/service_traits.h>


#include <client_server/project1Request.h>
#include <client_server/project1Response.h>


namespace client_server
{

struct project1
{

typedef project1Request Request;
typedef project1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct project1
} // namespace client_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::client_server::project1 > {
  static const char* value()
  {
    return "9eb847f2c8e1ec0b49be817ba7ae5609";
  }

  static const char* value(const ::client_server::project1&) { return value(); }
};

template<>
struct DataType< ::client_server::project1 > {
  static const char* value()
  {
    return "client_server/project1";
  }

  static const char* value(const ::client_server::project1&) { return value(); }
};


// service_traits::MD5Sum< ::client_server::project1Request> should match
// service_traits::MD5Sum< ::client_server::project1 >
template<>
struct MD5Sum< ::client_server::project1Request>
{
  static const char* value()
  {
    return MD5Sum< ::client_server::project1 >::value();
  }
  static const char* value(const ::client_server::project1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::client_server::project1Request> should match
// service_traits::DataType< ::client_server::project1 >
template<>
struct DataType< ::client_server::project1Request>
{
  static const char* value()
  {
    return DataType< ::client_server::project1 >::value();
  }
  static const char* value(const ::client_server::project1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::client_server::project1Response> should match
// service_traits::MD5Sum< ::client_server::project1 >
template<>
struct MD5Sum< ::client_server::project1Response>
{
  static const char* value()
  {
    return MD5Sum< ::client_server::project1 >::value();
  }
  static const char* value(const ::client_server::project1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::client_server::project1Response> should match
// service_traits::DataType< ::client_server::project1 >
template<>
struct DataType< ::client_server::project1Response>
{
  static const char* value()
  {
    return DataType< ::client_server::project1 >::value();
  }
  static const char* value(const ::client_server::project1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIENT_SERVER_MESSAGE_PROJECT1_H
